# Generated by Django 5.1.6 on 2025-02-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_session_isreported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='report',
            field=models.TextField(default=''),
        ),
    ]
