# Generated by Django 5.1.6 on 2025-02-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_session_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodule',
            name='reportSystem',
            field=models.TextField(default=''),
        ),
    ]
