# Generated by Django 5.1.6 on 2025-02-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodule',
            name='profileImg',
            field=models.URLField(default=''),
        ),
    ]
