# Generated by Django 5.1.6 on 2025-02-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aimodule_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='isReported',
            field=models.BooleanField(default=False),
        ),
    ]
